language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: vtbDNtAIzKxG31isGQ6VhuRbdWjwHNgzPrYZKBoiL515KXpfyRSTDKs1rFLiCgE0djM5UZAEUNjBTPsL/TdEvk31Ob5Ma7GG24ud/aJ5oa1NG8kjoliLzlgjPTRhOGQlhvK4oRZEzmzLSYVdYykMq61UbBfNEMALJSDc8p1jCs5oMMh/tdp93nCjP3vRmWQstq2z6hj3o9EROQrksG8fx7o22w1XlKfRYaCmYfNOMDKKZITZcyinWf7p/BhjkdaqPQzZ23f+5JFi7YvPDMvCGjxIOyn07TbQsnu0jA/fFCUvNPjZdaInrTa54AB8Jh4H2/Tc0JbDhDgalgP3w+1eUs859ngI+V2pzOK1NsgEa92vh0lLdrvohCAJHEluqRU5ZVtlm7JvNb3PpDI2b06Knfr78ENTTrcu7ekiRs5Xlk1UeNZc8WnNNoRgzvAmVa3ztQZYK64q2XUJ8ThR6AKnVT5kRMswT4ue/q08o7BxYa0pH1mYkJS6ZpirGxYacrA5JT5jyqzJvmHXWh5FzSu5czeEQmByCD46ly+k0K2XfRlvqTxHthMFBatZN4S674Sg10xiU+2gf1pT+RntojSrqKW9nFiD219AhrCLq+vShYBQmgG9jCZzLkYp4Jm/uiLWbBzhYOXszodqzf0QqtvlJv3bDTbW2OyicfvtVdxc+ZU=
  app: stark-oasis-61249
  on:
    repo: TmothyMartel/blog-api-challenge
